### ISSUE TITLE
Request Number in addition to id

### ISSUE THREAD

**Issue by jonathanfield** [PTFS-Europe/koha#21]
Right now, the request has an internal database ID, most libraries will want a branch definable request number on top of this (probably defined in the library policy as a prefix string?). 

So, e.g.

MAIN-1
BRANCH-1

where MAIN and BRANCH are the prefix

**Comment by janetc** [comment]
Feedback from SLHL - this is definitely a requirement for them - BL use the number in correspondence and it helps identify the request quickly..

**Comment by a-sassmannshausen** [comment]
Argh. pressed wrong button. Now must retype. Bad 90's email writing flash-back!

Spoke to Janet about this.  I propose an addition to the ILL DSL in koha-conf.xml, so that a prefix can be set by branch, and/or borrower category and/or default (fall-back).

This prefix would simply be glued in front of the db id for display purposes and when communicating with the BL.  It would not be stored in the db.

Let me know if you can think of any downsides to this approach.

Alex

**Comment by jonathanfield** [comment]
I think that would be absolutely fine.

**Comment by a-sassmannshausen** [comment]
This is implemented in commit "d491f49 * Implement branch/borrower category prefixes."
Pushed to dev server.
