### ISSUE TITLE
reply_date  completion_date are NULL

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/koha#79]
Hi, in ill_requests reply_date and completion_date all seem to be NULL. 
I can see some requests in the timestamp in the staff client have a date, but are these not yet written back to the db?

**Comment by a-sassmannshausen** [comment]
I imagine this is particularly relevant to running reports.

Will look at this as an urgent issue.

**Comment by a-sassmannshausen** [comment]
As discussed, Timestamp and Reply Date are two different fields.
- Timestamp will be updated whenever the ILL is updated
- Reply Date will now be implemented so that it's label and display is configurable from the config file.
- In this way it will become a 'site local' field that can be manually updated.
- completion_date will be added when an "end" status has been reached.

**Comment by a-sassmannshausen** [comment]
Part 1 (Reply date) is implemented in commit 983ad87 and e90babc.

The label and whether to show the reply date is controlled by the <reply_date> element in koha-conf in the ILLModule config section (a value of 'hide' will hide the field, all else is considered a label).

Part 2 (Completion date) will be implemented with formalised statuses.
